<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Collecting Job Data Using APIs**

Estimated time needed: **45 to 60** minutes

## Objectives

After completing this lab, you will be able to:

*   Collect job data from Jobs API
*   Store the collected data into an excel spreadsheet.

> <strong>Note: Before starting with the assignment make sure to read all the instructions and then move ahead with the coding part.</strong>

#### Instructions

To run the actual lab, firstly you need to click on the [Jobs_API](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/Accessing%20Data%20Using%20APIs/Jobs_API.ipynb) notebook link. The file contains flask code which is required to run the Jobs API data.

Now, to run the code in the file that opens up follow the below steps.

Step1: Download the file.

Step2: Upload it on the IBM Watson studio. (If IBM Watson Cloud service does not work in your system, follow the alternate Step 2 below)

Step2(alternate): Upload it in your SN labs environment using the upload button which is highlighted in red in the image below:
Remember to upload this Jobs_API file in the same folder as your current .ipynb file

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/Accessing%20Data%20Using%20APIs/Upload.PNG" />

Step3:  Run all the cells of the Jobs_API file. (Even if you receive an asterik sign after running the last cell, the code works fine.)

If you want to learn more about flask, which is optional, you can click on this link [here](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/Accessing%20Data%20Using%20APIs/FLASK_API.md.html).

Once you run the flask code, you can start with your assignment.

## Dataset Used in this Assignment

The dataset used in this lab comes from the following source: [https://www.kaggle.com/promptcloud/jobs-on-naukricom](https://www.kaggle.com/promptcloud/jobs-on-naukricom?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2022-01-01) under the under a **Public Domain license**.

> Note: We are using a modified subset of that dataset for the lab, so to follow the lab instructions successfully please use the dataset provided with the lab, rather than the dataset from the original source.

The original dataset is a csv. We have converted the csv to json as per the requirement of the lab.

## Warm-Up Exercise

Before you attempt the actual lab, here is a fully solved warmup exercise that will help you to learn how to access an API.

Using an API, let us find out who currently are on the International Space Station (ISS).<br> The API at [http://api.open-notify.org/astros.json](http://api.open-notify.org/astros.json?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ) gives us the information of astronauts currently on ISS in json format.<br>
You can read more about this API at [http://open-notify.org/Open-Notify-API/People-In-Space/](http://open-notify.org/Open-Notify-API/People-In-Space?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

In [1]:
import requests # you need this module to make an API call
import pandas as pd

In [2]:
api_url = "http://api.open-notify.org/astros.json" # this url gives use the astronaut data

In [3]:
response = requests.get(api_url) # Call the API using the get method and store the
                                # output of the API call in a variable called response.

In [4]:
if response.ok:             # if all is well() no errors, no network timeouts)
    data = response.json()  # store the result in json format in a variable called data
                            # the variable data is of type dictionary.

In [5]:
print(data)   # print the data just to check the output or for debugging

{'number': 10, 'people': [{'name': 'Oleg Artemyev', 'craft': 'ISS'}, {'name': 'Denis Matveev', 'craft': 'ISS'}, {'name': 'Sergey Korsakov', 'craft': 'ISS'}, {'name': 'Kjell Lindgren', 'craft': 'ISS'}, {'name': 'Bob Hines', 'craft': 'ISS'}, {'name': 'Samantha Cristoforetti', 'craft': 'ISS'}, {'name': 'Jessica Watkins', 'craft': 'ISS'}, {'name': 'Cai Xuzhe', 'craft': 'Tiangong'}, {'name': 'Chen Dong', 'craft': 'Tiangong'}, {'name': 'Liu Yang', 'craft': 'Tiangong'}], 'message': 'success'}

Print the number of astronauts currently on ISS.

In [6]:
print(data.get('number'))

10

Print the names of the astronauts currently on ISS.

In [7]:
astronauts = data.get('people')
print("There are {} astronauts on ISS".format(len(astronauts)))
print("And their names are :")
for astronaut in astronauts:
    print(astronaut.get('name'))

There are 10 astronauts on ISS
And their names are :
Oleg Artemyev
Denis Matveev
Sergey Korsakov
Kjell Lindgren
Bob Hines
Samantha Cristoforetti
Jessica Watkins
Cai Xuzhe
Chen Dong
Liu Yang

Hope the warmup was helpful. Good luck with your next lab!

## Lab: Collect Jobs Data using Jobs API

### Objective: Determine the number of jobs currently open for various technologies  and for various locations

Collect the number of job postings for the following locations using the API:

*   Los Angeles
*   New York
*   San Francisco
*   Washington DC
*   Seattle
*   Austin
*   Detroit

In [8]:
#Import required libraries
import pandas as pd
import json

#### Write a function to get the number of jobs for the Python technology.<br>

> Note: While using the lab you need to pass the **payload** information for the **params** attribute in the form of **key** **value** pairs.

Refer the ungraded **rest api lab** in the course **Python for Data Science, AI & Development**  <a href="https://www.coursera.org/learn/python-for-applied-data-science-ai/ungradedLti/P6sW8/hands-on-lab-access-rest-apis-request-http?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2022-01-01">link</a>

##### The keys in the json are

*   Job Title

*   Job Experience Required

*   Key Skills

*   Role Category

*   Location

*   Functional Area

*   Industry

*   Role

You can also view  the json file contents  from the following <a href = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/Accessing%20Data%20Using%20APIs/jobs.json?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2022-01-01">json</a> URL.

In [11]:
import requests
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/Accessing%20Data%20Using%20APIs/jobs.json?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2022-01-01"

response = requests.get(url)
if response.ok:
    data2 = response.json()
print(data2[35])
print("Python" in data2[35].get("Key Skills"))

{'Id': 38, 'Job Title': 'nutanix sme', 'Job Experience Required': '15 - 20 yrs', 'Key Skills': 'Troubleshooting| DNS| DHCP| Monitoring| Virtualization| Shell scripting|Python| VMS| Open source| Archiving', 'Role Category': 'Technical Support', 'Location': 'Washington DC', 'Functional Area': 'IT Hardware , Technical Support , Telecom Engineering', 'Industry': 'IT-Software, Software Services', 'Role': 'Technical Support Manager'}
True

In [12]:
# api_url="http://127.0.0.1:5000/data"
def get_number_of_jobs_T(technology):
    
    #your code goes here
    number_of_jobs = 0
    response = requests.get(url)
    if response.ok:
        data = response.json()
        for i in range(len(data)):
            if technology.lower() in data[i].get("Key Skills").lower():
                number_of_jobs += 1
    
    return technology,number_of_jobs

Calling the function for Python and checking if it works.

In [13]:
get_number_of_jobs_T("Python")

('Python', 1173)

#### Write a function to find number of jobs in US for a location of your choice

In [14]:
def get_number_of_jobs_L(location):
    
    #your coe goes here
    number_of_jobs = 0
    response = requests.get(url)
    if response.ok:
        data = response.json()
        for i in range(len(data)):
            if location.lower() in data[i].get("Location").lower():
                number_of_jobs += 1
    
    return location,number_of_jobs

Call the function for Los Angeles and check if it is working.

In [15]:
#your code goes here
get_number_of_jobs_L("Los Angeles")

('Los Angeles', 640)

In [16]:
L= ["Los Angeles", "New York", "San Francisco", "Washington DC", "Seattle"]
for i in L:
    print(get_number_of_jobs_L(i))

('Los Angeles', 640)
('New York', 3226)
('San Francisco', 435)
('Washington DC', 5316)
('Seattle', 3375)

### Store the results in an excel file

Call the API for all the given technologies above and write the results in an excel spreadsheet.

If you do not know how create excel file using python, double click here for **hints**.

<!--

from openpyxl import Workbook        # import Workbook class from module openpyxl
wb=Workbook()                        # create a workbook object
ws=wb.active                         # use the active worksheet
ws.append(['Country','Continent'])   # add a row with two columns 'Country' and 'Continent'
ws.append(['Eygpt','Africa'])        # add a row with two columns 'Egypt' and 'Africa'
ws.append(['India','Asia'])          # add another row
ws.append(['France','Europe'])       # add another row
wb.save("countries.xlsx")            # save the workbook into a file called countries.xlsx


-->

Create a python list of all locations for which you need to find the number of jobs postings.

In [20]:
#your code goes here
locations_list = []
for i in range(len(data2)):
    if data2[i].get("Location") in locations_list:
        pass
    else:
        locations_list.append(data2[i].get("Location"))
locations_list.sort()
locations_list

['Austin',
 'Baltimore',
 'Boston',
 'Dallas',
 'Detroit',
 'Houston',
 'Los Angeles',
 'New Orleons',
 'New York',
 'Philadelphia',
 'San Francisco',
 'Seattle',
 'Washington DC']

Import libraries required to create excel spreadsheet

In [21]:
# your code goes here
!pip install openpyxl
from openpyxl import Workbook # import Workbook class from module openpyxl

Requirement already satisfied: openpyxl in /opt/conda/envs/Python-3.9/lib/python3.9/site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in /opt/conda/envs/Python-3.9/lib/python3.9/site-packages (from openpyxl) (1.1.0)

Create a workbook and select the active worksheet

In [22]:
# your code goes here
wb=Workbook() # create a workbook object
ws=wb.active # use the active worksheet

Find the number of jobs postings for each of the location in the above list.
Write the Location name and the number of jobs postings into the excel spreadsheet.

In [23]:
#your code goes here
ws.append(["Location","Number of Jobs Postings"]) # add a row with two columns

for i in locations_list:
    ws.append(get_number_of_jobs_L(i))

Save into an excel spreadsheet named 'job-postings.xlsx'.

In [24]:
#your code goes here
wb.save("job-postings.xlsx") # save the workbook into a file

In [25]:
job_data = pd.read_excel("job-postings.xlsx")
job_data

         Location  Number of Jobs Postings
0          Austin                      434
1       Baltimore                     1263
2          Boston                     2966
3          Dallas                     1208
4         Detroit                     3945
5         Houston                     3339
6     Los Angeles                      640
7     New Orleons                      817
8        New York                     3226
9    Philadelphia                       41
10  San Francisco                      435
11        Seattle                     3375
12  Washington DC                     5316

#### In the similar way, you can try for below given technologies and results  can be stored in an excel sheet.

Collect the number of job postings for the following languages using the API:

*   C
*   C#
*   C++
*   Java
*   JavaScript
*   Python
*   Scala
*   Oracle
*   SQL Server
*   MySQL Server
*   PostgreSQL
*   MongoDB

In [26]:
# your code goes here
languages_list = ["C", "C#", "C++", "Java", "JavaScript", "Python", "Scala", "Oracle", "SQL Server", "MySQL Server", "PostgreSQL", "MongoDB"]

wb2=Workbook() # create a workbook object
ws2=wb2.active # use the active worksheet

ws2.append(["Language","Number of Jobs Postings"]) # add a row with two columns

for i in languages_list:
    ws2.append(get_number_of_jobs_T(i))
    
wb2.save("job-postings_languages.xlsx") # save the workbook into a file

job_data2 = pd.read_excel("job-postings_languages.xlsx")
job_data2

        Language  Number of Jobs Postings
0              C                    25114
1             C#                      526
2            C++                      506
3           Java                     3428
4     JavaScript                     2248
5         Python                     1173
6          Scala                      138
7         Oracle                      899
8     SQL Server                      423
9   MySQL Server                        0
10    PostgreSQL                       86
11       MongoDB                      208

## Author

Ayushi Jain

### Other Contributors

Rav Ahuja

Lakshmi Holla

Malika

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2022-01-19        | 0.3     | Lakshmi Holla     | Added changes in the markdown      |
| 2021-06-25        | 0.2     | Malika            | Updated GitHub job json link       |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2022 IBM Corporation. All rights reserved.